(TeX-add-style-hook
 "Event_Coder_Manual"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("fontenc" "T1")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "memoir"
    "memoir10"
    "xcolor"
    "hyperref"
    "graphicx"
    "enumitem"
    "verbatim"
    "framed"
    "fontenc")
   (LaTeX-add-labels
    "chap:introduction"
    "sec:eventcoderprogram"
    "sec:partofbiggerprogram"
    "sec:disclaimers"
    "chap:preparations"
    "sec:allaboutdata"
    "sec:datasets"
    "fig:datasetstructure"
    "fig:csvfile"
    "sec:othernotesdatasets"
    "chap:usingtheprogram"
    "sec:loadingnewdataset"
    "fig:importoptions"
    "sec:importerrors"
    "fig:importerror"
    "sec:savingloadingdata"
    "fig:saveload"
    "sec:importingcodes"
    "fig:importcodesfig"
    "fig:importingcodeserror"
    "fig:importingcodesdiagram"
    "sec:problemsimportingcodes"
    "sec:navigatingdata"
    "fig:incidentsoverview"
    "fig:filternavigate"
    "sec:markingincidents"
    "fig:flaggedincident"
    "sec:memosincidents"
    "sec:filtering"
    "fig:filteringattributes"
    "sec:exportingdata"
    "fig:exportdialog"
    "sec:logfilesandexiting"
    "chap:usingtheprogram2"
    "sec:introductiontocoding"
    "sec:attributemodule"
    "sec:types of activity"
    "sec:colligatedevents"
    "sec:valuechanges"
    "fig:usesofattributes"
    "sec:creatingnewattributes"
    "fig:attributemodule"
    "fig:attributedialog"
    "fig:attributepool"
    "sec:editingattributes"
    "sec:removingattributes"
    "sec:incidentattributecategories"
    "fig:categorydialog"
    "fig:attributedialogwithcategories"
    "sec:assigningunassigningattributes"
    "fig:assignedattributes"
    "sec:navigatingattributes"
    "fig:navigatingattributes"
    "sec:relationshipmodule"
    "fig:relationshipmodule"
    "sec:creatingnewrelationships1"
    "fig:relationshipdialog"
    "sec:entities"
    "fig:entitydialog"
    "sec:relationshiptypes"
    "fig:relationshiptypedialog"
    "sec:creatingnewrelationships2"
    "fig:relationshipdialog2"
    "fig:relationshipdialog3"
    "sec:editingrelationships"
    "fig:relationshippool"
    "sec:removingrelationships"
    "sec:assigningunassigningrelationships"
    "fig:relationshipsassigned"
    "sec:navigatingrelationships"
    "fig:navigatingrelationships"
    "chap:whatisnext"
    "fig:network"
    "sec:graphdatabases"
    "fig:graphdatabaseexample"
    "fig:entitiestable"
    "fig:attributestable"
    "sec:creatingeventgraphs"
    "fig:eventgraph"
    "sec:futureexamples"
    "chap:contactdetails"))
 :latex)

